### ISSUE TITLE
Does this still work? Getting a 403

### ISSUE THREAD

**Issue by kchro3** [baselime/action-setup-baselime#4]
My github action is set up as:

```
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - uses: baselime/action-setup-baselime@v0.0.1
        with:
          baselime-api-key: ${{ secrets.BASELIME_API_KEY }}
          
      - name: 📍Create marker
        run: |
          baselime mark \
          --name Deployment \
          --url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          --metadata '${{ toJson(github) }}' \
          --service ${{ github.repository }}
```

I'm getting this:

```
baselime mark \
  --name Deployment \
  ... redacted
  shell: /usr/bin/bash -e {0}
Attention: Baselime now collects completely anonymous telemetry regarding usage. This is used to guide our roadmap.
You can learn more, including how to opt-out of this anonymous program, by heading over to:
https://baselime.io/docs/cli/anonymous-telemetry

- Creating marker
✖ Creating marker
Error - Forbidden
✖ Error - Request failed with status code 403
Use the --debug flag to view the complete stack trace.
Error: Process completed with exit code 1.
```

And i do have the secret set up
<img width="799" alt="Screenshot 2024-07-02 at 12 08 58 PM" src="https://github.com/baselime/action-setup-baselime/assets/62481661/c219e329-5c73-4928-b7d5-21cf64ba7460">
